/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-02-02 03:44:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.bar_005fview;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLDecoder;
import com.uh.vo.BoardVo;
import java.util.ArrayList;
import java.io.Console;

public final class left_005fbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.uh.vo.BoardVo");
    _jspx_imports_classes.add("java.net.URLDecoder");
    _jspx_imports_classes.add("java.io.Console");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
ArrayList<ArrayList<BoardVo>> returnList = (ArrayList<ArrayList<BoardVo>>)request.getAttribute("list"); 
    	String nick= (String)session.getAttribute("nick");
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- <link href=\"resources/CSSs/bar_css/left_bar.css\" rel=\"stylesheet\"> -->\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	@charset \"UTF-8\";\r\n");
      out.write(".context_container{\r\n");
      out.write("	margin-left:260px;\r\n");
      out.write("}\r\n");
      out.write(".left_bar_container{\r\n");
      out.write("	margin-top:77px;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	width: 250px;\r\n");
      out.write("	background-color: #f7f9fa;\r\n");
      out.write("	border: 1px solid #dae1e6;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".sign_info_container{\r\n");
      out.write("	width:90%;\r\n");
      out.write("	height: 200px;\r\n");
      out.write("	border:1px solid black;\r\n");
      out.write("	margin: 10px auto 10px auto;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write(".category_container{\r\n");
      out.write("	width:90%;\r\n");
      out.write("	border:1px solid black;\r\n");
      out.write("	margin: 10px auto 10px auto;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write(".board_fontsize{\r\n");
      out.write("	list-style:none;\r\n");
      out.write("	font-size: 5px;\r\n");
      out.write("}\r\n");
      out.write(".loginBtn{\r\n");
      out.write("	border: 1px solid #3c4790;\r\n");
      out.write("    background: #4a57a8;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    text-shadow: 0px 1px #343d8e;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    width: 95%;\r\n");
      out.write("    height: 40px; \r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".join\r\n");
      out.write("{\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	float: center;\r\n");
      out.write("	font-weight: 1px;\r\n");
      out.write("    color: #000000;\r\n");
      out.write("}\r\n");
      out.write(".join2\r\n");
      out.write("{\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login_msg\r\n");
      out.write("{\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	padding-left: 3px;\r\n");
      out.write("    color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("	/* 123123 */\r\n");
      out.write("	.board_fontsize{\r\n");
      out.write("	   font-size: 12px;\r\n");
      out.write("	   list-style: none;\r\n");
      out.write("	  \r\n");
      out.write("	}\r\n");
      out.write("	.board_name_style{\r\n");
      out.write("	   color: #3c4790;\r\n");
      out.write("	   margin-block-start: 1.33em;\r\n");
      out.write("       margin-block-end: 1.33em;\r\n");
      out.write("       margin-inline-start: 0px;\r\n");
      out.write("       margin-inline-end: 0px;\r\n");
      out.write("       font-weight: bold;\r\n");
      out.write("       \r\n");
      out.write("	}\r\n");
      out.write("	.board_name{\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("	.board_name:hover {\r\n");
      out.write("			background-color: #f7f9fa;\r\n");
      out.write("	}\r\n");
      out.write("	.decoration_style{\r\n");
      out.write("	   text-decoration: none;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write(" a:link { color: black; text-decoration: none;}\r\n");
      out.write(" a:visited { color: black; text-decoration: none;}\r\n");
      out.write(" a:hover { color: black; text-decoration: none;}\r\n");
      out.write("	.cat{\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function goBoardMain(post_board_name){\r\n");
      out.write("			location.href='board_main?post_board_name='+post_board_name;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"left_bar_container\">\r\n");
      out.write("\r\n");
      out.write("	<!-- 회원 정보창 -->\r\n");
      out.write("	<div class=\"sign_info_container\">	\r\n");
      out.write("	");
if(nick==null){ 
      out.write("\r\n");
      out.write("		<p class=\"login_msg\">로그인 후에만 이용이 가능합니다.</p>\r\n");
      out.write("		<div class=\"logjoin\"style=\"text-align: center; width: 100%;\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<input class=\"loginBtn\" type=\"button\" value=\"로그인\" onclick='location.href=\"sign_in\"' >\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"join2\">\r\n");
      out.write("				<a href=\"sign_agree\" class=\"join\">회원가입</a>\r\n");
      out.write("			</div>	\r\n");
      out.write("		</div>\r\n");
      out.write("	");
}else{ 
      out.write("\r\n");
      out.write("	<div class=\"join2\" style=\"text-align: center;margin-top: 10px;\">\r\n");
      out.write("			<p >");
      out.print(nick);
      out.write("님 환영합니다.</p>	\r\n");
      out.write("			<br>\r\n");
      out.write("			<a href='board_main?post_board_name=ALL&search_mode=post_member_nick&search_str=");
      out.print(nick);
      out.write("&my=my' class=\"join\" >\r\n");
      out.write("				내가 쓴 게시물\r\n");
      out.write("			</a>\r\n");
      out.write("			<br><br>\r\n");
      out.write("			<a href=\"sign_out\" class=\"join\" >로그아웃</a>\r\n");
      out.write("			\r\n");
      out.write("		</div>	\r\n");
      out.write("	");
} 
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 카테고리 -->\r\n");
      out.write("	<div class=\"category_container\">\r\n");
      out.write("	 <span style=\"font-size: 24px;\">전체 게시판</span><br>\r\n");
      out.write("	<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("	<script src=\"resources/JSs/ajax/ajax.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("			");
Cookie cookies[]=request.getCookies();
      out.write("\r\n");
      out.write("			");
for(int i=0;i<cookies.length;i++){
      out.write("\r\n");
      out.write("				");
if(cookies[i].getName().contains("carTag")){
      out.write("\r\n");
      out.write("					displayTag(");
      out.print(cookies[i].getName().replaceFirst("carTag", ""));
      out.write(");\r\n");
      out.write("				");
}
      out.write("\r\n");
      out.write("			");
}
      out.write("\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		function tagClick(j){\r\n");
      out.write("			ajaxDo(\"displayTag?j=\"+j,\"\");\r\n");
      out.write("			displayTag(j);\r\n");
      out.write("			}\r\n");
      out.write("		function displayTag(j){			\r\n");
      out.write("				var tags=document.getElementsByClassName('tag'+j);\r\n");
      out.write("				if(tags[0].style.display=='none'){\r\n");
      out.write("					for(i=0;i<tags.length;i++)\r\n");
      out.write("						tags[i].style.display='block';\r\n");
      out.write("						$(\"#tagPluse\"+j).text(\"-\");\r\n");
      out.write("				}else{\r\n");
      out.write("					for(i=0;i<tags.length;i++)\r\n");
      out.write("						tags[i].style.display='none';\r\n");
      out.write("					$(\"#tagPluse\"+j).text(\"+\");\r\n");
      out.write("					}\r\n");
      out.write("			}\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	");
    
    	String str="";
		for(int j=0;j<returnList.size();j++) {
		
			for(int i=0;i<returnList.get(j).size();i++) {
				
				if(!returnList.get(j).get(i).getBoard_category().equals(str)) {
					str=returnList.get(j).get(i).getBoard_category();
					out.println("<span class='cat' onclick='tagClick("+j+")' style='color:blue;font-size:18px;'>"+returnList.get(j).get(i).getBoard_category()+"("+returnList.get(j).size()+")</span>");
					out.println("<span id='tagPluse"+j+"' style='font-size:13px'>+</span><br>");
				}
			
				out.println(" <a class='tag"+j+"' href='board_main?post_board_name="+returnList.get(j).get(i).getBoard_name()+"' style='display:none'>");
				out.println("<p> &nbsp &nbsp &nbsp &nbsp"+returnList.get(j).get(i).getBoard_name()+"</p></a>");
				
						
			}
		
			
		} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 광고 -->\r\n");
      out.write("	<div style=\"margin: 0px auto; width: 95%; \" >\r\n");
      out.write("		<iframe src=\"https://adpick.co.kr/nativeAD/ad.php?bannerType=type8&limit=1&affid=c2a9f2&frameId=AdpickAdFrame_2020920%40223443&popup=false\" width=\"100%\" frameborder=\"0\" scrolling=\"no\" data-adpick_nativeAD id=\"AdpickAdFrame_2020920@223443\" style=\"margin: 5px auto;\"></iframe>\r\n");
      out.write("		<script src=\"https://adpick.co.kr/nativeAD/script.js\" async=\"true\"></script>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
