/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-02-02 03:44:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board_005fview;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.uh.vo.PostVo;
import java.util.ArrayList;

public final class board_005fkit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.uh.vo.PostVo");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    String post_board_name=request.getParameter("post_board_name");
	String page_num=request.getParameter("page_num");
	String search_mode=request.getParameter("search_mode");
	String search_str=request.getParameter("search_str");
	String car=(String)request.getAttribute("car");
	String my=request.getParameter("my");
	String main=request.getParameter("main");
	String nick=(String)session.getAttribute("nick");
	if(nick==null){
		nick="";
	}
	
	if(my==null){
		my="";
	}
	
	if(main==null){
		main="";
	}
	
    
      out.write("   \r\n");
      out.write("    ");

    ArrayList<PostVo> list=(ArrayList<PostVo>)request.getAttribute("list");
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("	\r\n");
      out.write("		.board_container{\r\n");
      out.write("			width: 1000px;\r\n");
      out.write("			margin-left: 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		/* 게시판 이름 */\r\n");
      out.write("		.board_name_div{		/* board_main 에서 사용 , post_main에서 미사용 */\r\n");
      out.write("			font-size: 43px;	\r\n");
      out.write("			font-family: 'Do Hyeon', sans-serif;	\r\n");
      out.write("			padding: 0 0 15px 0;\r\n");
      out.write("			margin-left: 20px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.board_go_post{\r\n");
      out.write("		\r\n");
      out.write("			float:right;\r\n");
      out.write("			margin: 5px 5px;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("		}	\r\n");
      out.write("\r\n");
      out.write("		/* 게시물들 출력부 */\r\n");
      out.write("		.board_post_container{\r\n");
      out.write("			background-color: #f7f9fa;\r\n");
      out.write("			border: 1px solid #dae1e6;\r\n");
      out.write("			border-radius: 0.5%;\r\n");
      out.write("		}\r\n");
      out.write("				/* table부 */\r\n");
      out.write("			table{\r\n");
      out.write("				border-collapse: collapse;\r\n");
      out.write("			}\r\n");
      out.write("			.board_post_header_tr{\r\n");
      out.write("				height: 42px;\r\n");
      out.write("	\r\n");
      out.write("			}\r\n");
      out.write("			th{\r\n");
      out.write("				font-size: 23px;	\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("			.board_post_tr{\r\n");
      out.write("				text-align: center;\r\n");
      out.write("				scope:rowgroup;\r\n");
      out.write("				height: 38px;\r\n");
      out.write("			}\r\n");
      out.write("			.board_post_tr:hover{\r\n");
      out.write("				background-color:white; \r\n");
      out.write("				cursor: pointer;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			td{\r\n");
      out.write("				font-size: 20px;\r\n");
      out.write("				overflow:hidden;\r\n");
      out.write("				white-space : nowrap;\r\n");
      out.write("				text-overflow: ellipsis;\r\n");
      out.write("			}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		/* 페이지 번호부 */               \r\n");
      out.write("		.board_page_num_div{\r\n");
      out.write("			font-family: 'Do Hyeon', sans-serif;	\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			font-size: 30px;\r\n");
      out.write("			padding: 10px 0 15px 0;\r\n");
      out.write("		}\r\n");
      out.write("		/* 게시판에서 검색부 */\r\n");
      out.write("		.board_search_div{\r\n");
      out.write("			padding: 0 0 30px 0;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			margin-top: -50px;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		#sub_board_title:hover   { text-decoration:underline; }\r\n");
      out.write("	\r\n");
      out.write("	</style>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function go_post(post_idx){\r\n");
      out.write("			location.href='post?post_idx='+post_idx+'&post_board_name=");
      out.print(post_board_name);
      out.write("'+\r\n");
      out.write("			'&search_mode=");
      out.print(search_mode);
      out.write("&search_str=");
      out.print(search_str);
      out.write("&car=");
      out.print(car);
      out.write("&my=");
      out.print(my);
      out.write("&main=");
      out.print(main);
      out.write("';	\r\n");
      out.write("		\r\n");
      out.write("		}\r\n");
      out.write("		function create_post(){\r\n");
      out.write("			location.href='post_create?post_board_name=");
      out.print(post_board_name);
      out.write("&page_num=");
      out.print(page_num);
      out.write("'+\r\n");
      out.write("			'&search_mode=");
      out.print(search_mode);
      out.write("&search_str=");
      out.print(search_str);
      out.write("&car=");
      out.print(car);
      out.write("';\r\n");
      out.write("			}\r\n");
      out.write("		function goPage(i){\r\n");
      out.write("			get_board_kit(i,'");
      out.print(post_board_name);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(search_mode);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(search_str);
      out.write("');\r\n");
      out.write("			}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"board_container\">\r\n");
      out.write("	\r\n");
      out.write("			<!-- 게시판 이름 -->\r\n");
      out.write("		");
if(my!=null&&my.equals("my")) {
      out.write("\r\n");
      out.write("			<div class=\"board_name_div\"><!-- style은 board_kit.css에 정의  -->\r\n");
      out.write("				<span onclick=\"location.href='board_main?post_board_name=ALL&search_mode=post_title&search_str=");
      out.print(nick );
      out.write("&my=my'\" style=\"cursor: pointer;\">내 게시글</span>		\r\n");
      out.write("			</div>\r\n");
      out.write("		");
}else if(main!=null&&main.equals("main")){
      out.write("\r\n");
      out.write("			<div class=\"board_name_div\"><!-- style은 board_kit.css에 정의  -->\r\n");
      out.write("				<span onclick=\"location.href='main?main=main'\" style=\"cursor: pointer;\">레전드 놀이터!</span>			\r\n");
      out.write("			</div>\r\n");
      out.write("		");
}else{ 
      out.write("\r\n");
      out.write("			");
if(!post_board_name.equals("ALL")) {
      out.write("\r\n");
      out.write("			<div class=\"board_name_div\"><!-- style은 board_kit.css에 정의  -->\r\n");
      out.write("				<span onclick=\"location.href='board_main?post_board_name=");
      out.print( post_board_name);
      out.write("'\" style=\"cursor: pointer;\">");
      out.print( post_board_name);
      out.write(" 게시판</span>\r\n");
      out.write("				<span style=\"font-size: 15px;\"> ");
      out.print(car);
      out.write(' ');
      out.write('>');
      out.write(' ');
      out.print( post_board_name );
      out.write(" </span>\r\n");
      out.write("			</div>\r\n");
      out.write("			");
} else {
      out.write("\r\n");
      out.write("			<div class=\"board_name_div\"><!-- style은 board_kit.css에 정의  -->\r\n");
      out.write("				<span onclick=\"location.href='board_main?post_board_name=ALL&search_mode=");
      out.print(search_mode );
      out.write("&search_str=");
      out.print(search_str );
      out.write("'\" style=\"cursor: pointer;\">전체 검색</span>\r\n");
      out.write("				<span style=\"font-size: 15px;\">  > ");
      out.print(search_str );
      out.write(" </span>\r\n");
      out.write("			</div>\r\n");
      out.write("			");
}
      out.write("\r\n");
      out.write("		");
}
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		");
if(!post_board_name.equals("ALL")){ 
      out.write("\r\n");
      out.write("		<input class=\"board_go_post\" type=\"button\" value=\"글작성\" onclick=\"create_post()\">\r\n");
      out.write("		");
}
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("			\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		<!-- 게시 글들 담는 div -->\r\n");
      out.write("		<div class=\"board_post_container\">\r\n");
      out.write("			<table style=\"width: 100%; table-layout:fixed;border: 0px;\">\r\n");
      out.write("				<tr class=\"board_post_header_tr\">\r\n");
      out.write("					<th width=80>글번호</th>\r\n");
      out.write("					<th width=\"37\"></th>\r\n");
      out.write("					<th width=\"400\">제목</th>\r\n");
      out.write("					<th width=\"120\">글쓴이</th>\r\n");
      out.write("					<th width=\"170\">작성일</th>\r\n");
      out.write("					<th width=\"50\">조회</th>\r\n");
      out.write("					<th width=\"50\">추천</th>\r\n");
      out.write("					<th width=\"50\">댓글</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("		\r\n");
      out.write("					");
for(int i=0;i<list.size();i++){ 
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("						");
 String title=list.get(i).getPost_title();
      out.write("\r\n");
      out.write("						");
if(!search_str.equals("null")){ 
      out.write("\r\n");
      out.write("						");
 title=title.replaceAll(search_str, "<span style='background-color: #cffcd8;'>"+search_str+"</span>");
      out.write("\r\n");
      out.write("						");
} 
      out.write("				\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						");
if(list.get(i).getPost_title().equals("삭제된게시글입니다.")) {
      out.write("\r\n");
      out.write("						<tr class=\"board_post_tr\" style=\"background-color: #e3e3e3; cursor:default;\" onclick=\"alert('삭제된게시물');\">\r\n");
      out.write("						");
}else{ 
      out.write("\r\n");
      out.write("						<tr class=\"board_post_tr\" onclick=\"go_post(");
      out.print(list.get(i).getPost_idx());
      out.write(")\">\r\n");
      out.write("						");
}
      out.write("\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("							<td>");
      out.print(list.get(i).getPost_idx());
      out.write("</td>\r\n");
      out.write("							<td><img src='resources/imgs/board_img/");
      out.print(list.get(i).getPost_img()!=null?"YesImg.png":"NoImg.png" );
      out.write("' width=\"35\" height=\"35\" style=\"float: left;\"></td>\r\n");
      out.write("							");
if(!post_board_name.equals("ALL")){ 
      out.write("\r\n");
      out.write("								<td style=\"text-align: left;\">");
      out.print(title);
      out.write("</td>\r\n");
      out.write("							");
}else{ 
      out.write("\r\n");
      out.write("								<td style=\"text-align: left;\">\r\n");
      out.write("								<span id=\"sub_board_title\" style=\"font-size: 15px;color: blue;\" \r\n");
      out.write("								onclick=\"event.cancelBubble=true;location.href='board_main?post_board_name=");
      out.print(list.get(i).getPost_board_name());
      out.write("'\">\r\n");
      out.write("									");
      out.print(list.get(i).getPost_board_name());
      out.write(" > \r\n");
      out.write("								</span>\r\n");
      out.write("								");
      out.print(title);
      out.write("</td>\r\n");
      out.write("							");
}
      out.write("\r\n");
      out.write("							<td>");
      out.print(list.get(i).getPost_member_nick());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(list.get(i).getPost_date());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(list.get(i).getPost_view());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(list.get(i).getLike_count() );
      out.write("</td>\r\n");
      out.write("							<td>0</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("			</table>	\r\n");
      out.write("			");
if(list.size()==0){ 
      out.write("\r\n");
      out.write("				 <h1 style=\"text-align: center;\">검색 결과가 없습니다.</h1>\r\n");
      out.write("				");
 }
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<!-- 게시판 페이지 -->\r\n");
      out.write("		<div class=\"board_page_num_div\">\r\n");
      out.write("			");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageMenu }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("		<!-- 게시판 내 검색창 div -->\r\n");
      out.write("		<div class=\"board_search_div\" >	\r\n");
      out.write("		");
if(!post_board_name.equals("ALL")){ 
      out.write("\r\n");
      out.write("			<input class=\"board_go_post\" type=\"button\" value=\"글작성\" onclick=\"create_post()\">\r\n");
      out.write("		");
}else{
      out.write("\r\n");
      out.write("			<input class=\"board_go_post\" type=\"button\" value=\"글작성\" onclick=\"create_post()\" style=\"visibility: hidden;\">\r\n");
      out.write("		");
}
      out.write("\r\n");
      out.write("		<br><br>\r\n");
      out.write("	\r\n");
      out.write("					<form action=\"board_main\">\r\n");
      out.write("						<input type=\"hidden\" name=\"post_board_name\" value='");
      out.print(post_board_name);
      out.write("'>\r\n");
      out.write("						<input type=\"hidden\" name=\"page_num\" value='");
      out.print(page_num);
      out.write("'>\r\n");
      out.write("						<select class=\"search_combo\" name=\"search_mode\" >\r\n");
      out.write("				    		<option value=\"post_title\">제목</option>\r\n");
      out.write("				    		<option value=\"post_member_nick\">작성자</option>\r\n");
      out.write("						</select>\r\n");
      out.write("						<input class=\"search_input\" name=\"search_str\" type=\"text\" placeholder=\"search in board\" autocomplete=\"off\" onkeydown=\"search_this(this)\">\r\n");
      out.write("					\r\n");
      out.write("					</form>						\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
