/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-02-02 03:45:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.reply_005fview;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.uh.vo.ReplyVo;
import java.util.ArrayList;

public final class reply_005fkit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.uh.vo.ReplyVo");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	
	String member_idx = request.getParameter("member_idx"); // 회원 idx
	String post_idx = request.getParameter("post_idx"); // 게시물 번호
	String post_board_name = request.getParameter("post_board_name"); //게시판 이름
	String page_num = request.getParameter("page_num"); // 페이지 번호
	String search_mode = request.getParameter("search_mode");
	String search_str = request.getParameter("search_str");
    

      out.write(' ');
      out.write('\n');
      out.write('\n');

	ArrayList<ReplyVo> reply_list = (ArrayList<ReplyVo>)request.getAttribute("reply_list");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("	.board_reply_content_btn{\n");
      out.write("		text-align: right;\n");
      out.write("		margin-bottom: 10px;\n");
      out.write("		margin-right: 5px;\n");
      out.write("	}\n");
      out.write("	.text_counting{\n");
      out.write("		color: #aaa;\n");
      out.write("		float: left;\n");
      out.write("		margin-left: 5px;\n");
      out.write("	}\n");
      out.write("	.reply_text{\n");
      out.write("		resize: none;\n");
      out.write("	}\n");
      out.write("	.reply_date{\n");
      out.write("		font-size: 10px;\n");
      out.write("		 color: gray;\n");
      out.write("		 text-align: right;\n");
      out.write("		 \n");
      out.write("	}\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	$('.reply_text').on('keydown', function() {\n");
      out.write("		\n");
      out.write("		var content = $(this).val();\n");
      out.write("		$('#text_counting').html(\"(\"+content.length+\" / 최대 200자)\");    //글자수 실시간 카운팅\n");
      out.write("		\n");
      out.write("		if($(this).val().length > 200) {\n");
      out.write("			alert(\"글자수 제한이 있습니다.\");\n");
      out.write("			$(this).val($(this).val().substring(0, 200));\n");
      out.write("			\n");
      out.write("		}\n");
      out.write("\n");
      out.write("			\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	function reply_insert(f) {\n");
      out.write("		if(f.post_reply_text.value.trim() == \"\"){\n");
      out.write("			alert(\"내용을 입력해주세요\");\n");
      out.write("			return false;\n");
      out.write("		}else{\n");
      out.write("			var text = f.post_reply_text.value;\n");
      out.write("			f.post_reply_text.value=text.replace(/(\\n|\\r\\n)/g, '<br>');\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function reply_insert(f) {\n");
      out.write("		");
if(session.getAttribute("nick")==null||session.getAttribute("nick").equals("")){
      out.write("\n");
      out.write("			location.href='notSignIn';\n");
      out.write("		");
}else{
      out.write("\n");
      out.write("		if($(\"#reply_text\").val().trim() == \"\"){\n");
      out.write("			alert(\"내용을 입력해주세요\");\n");
      out.write("			return;\n");
      out.write("		}else{\n");
      out.write("			$.ajax({\n");
      out.write("				type:'get',\n");
      out.write("				async:false,\n");
      out.write("				url:'reply_insert.do?post_idx=' + ");
      out.print(post_idx);
      out.write(" + '&reply_con=' + $('#reply_text').val(),\n");
      out.write("				success: function(data) {\n");
      out.write("					\n");
      out.write("				}\n");
      out.write("			}); // ajax\n");
      out.write("			\n");
      out.write("			reply_select('");
      out.print(member_idx);
      out.write('\'');
      out.write(',');
      out.print(post_idx);
      out.write(',');
      out.write(' ');
      out.print(page_num);
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print(post_board_name);
      out.write("', '");
      out.print(search_mode);
      out.write("', '");
      out.print(search_str);
      out.write("');\n");
      out.write("		}\n");
      out.write("		");
}
      out.write("\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	function look(i) {\n");
      out.write("		var test1 = document.getElementById('btn'+i);\n");
      out.write("		var test2 = document.getElementById('btnn'+i);\n");
      out.write("		var test3 = document.getElementById('btnns'+i);\n");
      out.write("		test1.style.display = 'inline';\n");
      out.write("		test2.style.display = 'inline';\n");
      out.write("		test3.style.display = 'inline';\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function out(i) {\n");
      out.write("		var test1 = document.getElementById('btn'+i);\n");
      out.write("		var test2 = document.getElementById('btnn'+i);\n");
      out.write("		var test3 = document.getElementById('btnns'+i);\n");
      out.write("		test1.style.display = 'none';\n");
      out.write("		test2.style.display = 'none';\n");
      out.write("		test3.style.display = 'none';\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script src=\"resources/JSs/reply_js/reply.js\"></script> <!-- js 파일 로드 -->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<div class=\"board_reply_container\">\n");
      out.write("	<div style=\"width:100%; \">\n");
      out.write("		<form action=\"reply_insert.do\" method=\"post\">\n");
      out.write("		\n");
      out.write("			<input type=\"hidden\" name=member_idx value='");
      out.print( member_idx );
      out.write("'>\n");
      out.write("			<input type=\"hidden\" name=post_idx value='");
      out.print( post_idx );
      out.write("'>\n");
      out.write("			\n");
      out.write("			<input type=\"hidden\" name=page_num value='");
      out.print( page_num );
      out.write("'>\n");
      out.write("			<input type=\"hidden\" name=post_board_name value='");
      out.print( post_board_name );
      out.write("'>\n");
      out.write("			<input type=\"hidden\" name=search_mode value='");
      out.print(search_mode);
      out.write("'>\n");
      out.write("			<input type=\"hidden\" name=search_str value='");
      out.print(search_str);
      out.write("'>\n");
      out.write("			\n");
      out.write("			<div class=\"board_reply_content\" style=\"margin-bottom: 10px;\">\n");
      out.write("				<textarea class=\"reply_text\" name=\"reply_text\" id=\"reply_text\" rows=\"5\" cols=\"139\" placeholder=\"댓글\"></textarea>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			\n");
      out.write("			<div class=\"board_reply_content_btn\" >\n");
      out.write("				<span class=\"text_counting\" id=\"text_counting\">(0 / 최대 200자)</span>\n");
      out.write("				<input class=\"btnreply\" type=\"button\" value=\"등록\" onclick=\"reply_insert(this)\" style=\"width:100px; height:40px;\"/>\n");
      out.write("				<hr>\n");
      out.write("			</div>\n");
      out.write("		</form>		\n");
      out.write("				\n");
      out.write("		<div>\n");
      out.write("			<table>\n");
      out.write("			");
 if(reply_list.size() != 0){ 
      out.write("\n");
      out.write("				");
for (int i=0; i<reply_list.size(); i++) {
      out.write("\n");
      out.write("					<tr>\n");
      out.write("						<td>");
      out.print( reply_list.get(i).getReply_member_nick() );
      out.write("</td>\n");
      out.write("						<td style=\"width: 75%;white-space:normal; word-break:break-all;\">");
      out.print( reply_list.get(i).getReply_con());
      out.write("</td>\n");
      out.write("						<td style=\"width: 10%\" class=\"reply_date\">\n");
      out.write("							");
      out.print( reply_list.get(i).getReply_date() );
      out.write("\n");
      out.write("							<input class=\"btndap");
      out.print( i );
      out.write("\" type=\"button\" value=\"답글\" onclick=\"look(");
      out.print( i );
      out.write(")\" />\n");
      out.write("						</td>		\n");
      out.write("					</tr>\n");
      out.write("					\n");
      out.write("					<tr>\n");
      out.write("						<td></td>\n");
      out.write("						<td>\n");
      out.write("							<textarea id=\"btn");
      out.print( i );
      out.write("\" class=\"btn");
      out.print( i );
      out.write("\" style=\"display: none\" class=\"reply_text\" cols=\"50\" rows=\"1\" placeholder=\"답글입력\"></textarea>\n");
      out.write("							<input id=\"btnn");
      out.print( i );
      out.write("\" class=\"btnn");
      out.print( i );
      out.write("\" style=\"display: none\" type=\"button\" value=\"답글달기\">\n");
      out.write("							<input id=\"btnns");
      out.print( i );
      out.write("\" class=\"btnn");
      out.print( i );
      out.write("\" style=\"display: none\" type=\"button\" value=\"취소\" onclick=\"out(");
      out.print( i );
      out.write(")\">\n");
      out.write("						</td>\n");
      out.write("						<td></td>\n");
      out.write("					</tr>\n");
      out.write("				");
} 
      out.write("	\n");
      out.write("			");
} 
      out.write("	\n");
      out.write("			<br>\n");
      out.write("			</table>\n");
      out.write("			<br><br><br>\n");
      out.write("			\n");
      out.write("		</div>			 		\n");
      out.write("	</div>\n");
      out.write("</div>	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
